version: '3.8'

services:
  frontend: 
    image: pranavgawas/projectfrontend-v1:1.0.0

  backend:
    image: pranavgawas/vehicleconfiguratorapp:1.0.0
    environment:
      - SPRING_DATASOURCE_URL="jdbc:mysql://mydb:3306/project?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false"
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mydb

  mydb:
    image: mysql
    environment:
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=root
    volume:
      - ./data:var/lib/mysql
