version: '3.8'

services:
  app:
    image: pranavgawas/vehicleconfigurationapp:1.0.0
    ports:
      -8080:8080
    environment:
      - SPRING DATASOURCE_URL: jdbc:mysql://db:3306/project?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING DATASOURCE_USERNAME: admin
      - SPRING DATASOURCE_PASSWORD: root
    depends_on:
      - mydb

  mydb:
    image: mysql:8.0.27
    environment:
      - DATABASE_HOST: docker-mysql
      - DATABASE_PORT: 3306
      - MYSQL ROOT PASSWORD: root
      - MYSQL DATABASE: Localspringbootdb
      - MYSQL_USER: admin
      - MYSQL PASSWORD: root

      